services:
  blog:
    # use the Dockerfile in "." dir to build image
    build: .
    container_name: my-blog
    restart: always
    ports:
      - "8000:8000"
    volumes:
      # map current dir (including `mkdocs.yml` and `docs/`) to the container's `/docs` dir
      - ./:/docs
      # synchronize time zone
      - /etc/localtime:/etc/localtime:ro
    # start
    command: [ "serve", "--dev-addr=0.0.0.0:8000" ]
